<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\NostrRelay.Core\NostrRelay.Core.csproj" />
    <ProjectReference Include="..\..\src\NostrRelay.Server\NostrRelay.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="NBitcoin.Secp256k1" Version="4.0.1" />
  </ItemGroup>


</Project>
