// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NostrRelay.Storage.Sqlite;

#nullable disable

namespace NostrRelay.Storage.Sqlite.Migrations
{
    [DbContext(typeof(NostrRelayDbContext))]
    [Migration("20260818142720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("NostrRelay.Storage.Sqlite.EventTagEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tag_name");

                    b.Property<string>("TagValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tag_value");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "idx_event_tags_event_id");

                    b.HasIndex(new[] { "TagName", "TagValue" }, "idx_event_tags_name_value");

                    b.ToTable("event_tags");
                });

            modelBuilder.Entity("NostrRelay.Storage.Sqlite.NostrEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DTag")
                        .HasColumnType("TEXT")
                        .HasColumnName("d_tag");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Pubkey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pubkey");

                    b.Property<string>("Sig")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sig");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_events_created_at");

                    b.HasIndex(new[] { "ExpiresAt" }, "idx_events_expires_at");

                    b.HasIndex(new[] { "Kind", "CreatedAt" }, "idx_events_kind_created_at");

                    b.HasIndex(new[] { "Pubkey", "Kind" }, "idx_events_pubkey_kind");

                    b.HasIndex(new[] { "Pubkey", "Kind", "DTag" }, "idx_events_pubkey_kind_dtag");

                    b.ToTable("events");
                });

            modelBuilder.Entity("NostrRelay.Storage.Sqlite.EventTagEntity", b =>
                {
                    b.HasOne("NostrRelay.Storage.Sqlite.NostrEventEntity", "Event")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("NostrRelay.Storage.Sqlite.NostrEventEntity", b =>
                {
                    b.Navigation("EventTags");
                });
#pragma warning restore 612, 618
        }
    }
}
