// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NostrRelay.Storage.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NostrRelay.Storage.Postgres.Migrations
{
    [DbContext(typeof(NostrRelayDbContext))]
    [Migration("20260818140322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NostrRelay.Storage.Postgres.EventTagEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("event_id");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_name");

                    b.Property<string>("TagValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_value");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "idx_event_tags_event_id");

                    b.HasIndex(new[] { "TagName", "TagValue" }, "idx_event_tags_name_value");

                    b.ToTable("event_tags");
                });

            modelBuilder.Entity("NostrRelay.Storage.Postgres.NostrEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(64)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("DTag")
                        .HasColumnType("text")
                        .HasColumnName("d_tag");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Pubkey")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("pubkey");

                    b.Property<string>("Sig")
                        .IsRequired()
                        .HasColumnType("char(128)")
                        .HasColumnName("sig");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("TagsJson")
                        .HasDatabaseName("idx_events_tags_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TagsJson"), "gin");

                    b.HasIndex("Pubkey", "Kind")
                        .IsUnique()
                        .HasDatabaseName("uq_events_replaceable")
                        .HasFilter("kind = 0 OR kind = 3 OR (kind >= 10000 AND kind < 20000)");

                    b.HasIndex("Pubkey", "Kind", "DTag")
                        .IsUnique()
                        .HasDatabaseName("uq_events_addressable")
                        .HasFilter("kind >= 30000 AND kind < 40000");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_events_created_at");

                    b.HasIndex(new[] { "ExpiresAt" }, "idx_events_expires_at");

                    b.HasIndex(new[] { "Kind", "CreatedAt" }, "idx_events_kind_created_at");

                    b.HasIndex(new[] { "Pubkey", "Kind" }, "idx_events_pubkey_kind");

                    b.HasIndex(new[] { "Pubkey", "Kind", "DTag" }, "idx_events_pubkey_kind_dtag");

                    b.ToTable("events");
                });

            modelBuilder.Entity("NostrRelay.Storage.Postgres.EventTagEntity", b =>
                {
                    b.HasOne("NostrRelay.Storage.Postgres.NostrEventEntity", "Event")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("NostrRelay.Storage.Postgres.NostrEventEntity", b =>
                {
                    b.Navigation("EventTags");
                });
#pragma warning restore 612, 618
        }
    }
}
